apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  restartPolicy: Never
  containers:
  - name: postgres
    image: {{ postgres.image.name }}
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        add: []
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      seLinuxOptions: {}
    resources:
      requests:
        memory: {{ postgres.resources.requests.memory }}
      limits:
        memory: {{ postgres.resources.limits.memory }}
    ports:
    - containerPort: {{ postgres.port }}
      protocol: tcp
    env:
    - name: POSTGRES_PASSWORD
      value: {{ postgres.password }}
    volumeMounts:
    - mountPath: /docker-entrypoint-initdb.d/initdb.sql
      name: initdb
      readOnly: true
    - mountPath: /var/lib/postgresql/data
      name: pgdata
  volumes:
  - name: initdb
    hostPath:
      path: /opt/kong/initdb.sql
  - name: pgdata
    persistentVolumeClaim:
      claimName: postgres-data
